sonar.projectKey=Foufou-exe_axelrod-rs
sonar.organization=foufou-exe


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=axelrod-rs
sonar.projectVersion=0.2.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclusions for files that should not be analyzed. Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.exclusions=**/target/**, **/tests/**, **/examples/**
# Additional parameters can be set below. For more information, see the SonarCloud documentation.
#sonar.someProperty=value
